/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrizesIndexRouteImport } from './routes/prizes/index'
import { Route as LaureatesIndexRouteImport } from './routes/laureates/index'
import { Route as PrizesIdRouteImport } from './routes/prizes/$id'
import { Route as LaureatesIdRouteImport } from './routes/laureates/$id'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrizesIndexRoute = PrizesIndexRouteImport.update({
  id: '/prizes/',
  path: '/prizes/',
  getParentRoute: () => rootRouteImport,
} as any)
const LaureatesIndexRoute = LaureatesIndexRouteImport.update({
  id: '/laureates/',
  path: '/laureates/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrizesIdRoute = PrizesIdRouteImport.update({
  id: '/prizes/$id',
  path: '/prizes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LaureatesIdRoute = LaureatesIdRouteImport.update({
  id: '/laureates/$id',
  path: '/laureates/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/laureates/$id': typeof LaureatesIdRoute
  '/prizes/$id': typeof PrizesIdRoute
  '/laureates/': typeof LaureatesIndexRoute
  '/prizes/': typeof PrizesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/laureates/$id': typeof LaureatesIdRoute
  '/prizes/$id': typeof PrizesIdRoute
  '/laureates': typeof LaureatesIndexRoute
  '/prizes': typeof PrizesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/laureates/$id': typeof LaureatesIdRoute
  '/prizes/$id': typeof PrizesIdRoute
  '/laureates/': typeof LaureatesIndexRoute
  '/prizes/': typeof PrizesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/search'
    | '/laureates/$id'
    | '/prizes/$id'
    | '/laureates/'
    | '/prizes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/search'
    | '/laureates/$id'
    | '/prizes/$id'
    | '/laureates'
    | '/prizes'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/search'
    | '/laureates/$id'
    | '/prizes/$id'
    | '/laureates/'
    | '/prizes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  SearchRoute: typeof SearchRoute
  LaureatesIdRoute: typeof LaureatesIdRoute
  PrizesIdRoute: typeof PrizesIdRoute
  LaureatesIndexRoute: typeof LaureatesIndexRoute
  PrizesIndexRoute: typeof PrizesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prizes/': {
      id: '/prizes/'
      path: '/prizes'
      fullPath: '/prizes/'
      preLoaderRoute: typeof PrizesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laureates/': {
      id: '/laureates/'
      path: '/laureates'
      fullPath: '/laureates/'
      preLoaderRoute: typeof LaureatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prizes/$id': {
      id: '/prizes/$id'
      path: '/prizes/$id'
      fullPath: '/prizes/$id'
      preLoaderRoute: typeof PrizesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laureates/$id': {
      id: '/laureates/$id'
      path: '/laureates/$id'
      fullPath: '/laureates/$id'
      preLoaderRoute: typeof LaureatesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  SearchRoute: SearchRoute,
  LaureatesIdRoute: LaureatesIdRoute,
  PrizesIdRoute: PrizesIdRoute,
  LaureatesIndexRoute: LaureatesIndexRoute,
  PrizesIndexRoute: PrizesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
